spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1028073311661-5uarhmmi1cp02e5alb2d3vc2p27v9eps.apps.googleusercontent.com
            client-secret: S7lSc56CNdte155dzWJ_kGu8
            scope: profile, email